apiVersion: v2
appVersion: v1.5-rc
description: Roundcube
name: roundcube
version: 0.1.2
keywords:
  - roundcube
home: https://roundcube.net/
icon: https://roundcube.net/images/roundcube_logo_icon.svg
sources:
  - https://github.com/acjohnson/helm-charts/tree/master/charts/roundcube
  - https://github.com/roundcube/roundcubemail-docker
  - https://github.com/roundcube/roundcubemail
maintainers:
  - name: acjohnson
    email: acjohnson@pcdomain.com
