{{- if .Values.components.roundcube }}
{{- $fullName := include "roundcube.fullname" . -}}
{{- $namespace := include "roundcube.namespace" . -}}
{{- $labels := include "roundcube.labels" . | nindent 4 -}}
{{- $dummy := set . "component" .Values.roundcube.component }}
{{- $component := .component -}}
{{- with .Values.customConfigIncPhp -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $component }}-custom-config-inc-php
  namespace: {{ $namespace }}
  labels:
    {{- $labels }}
    component: {{ $component }}
data:
  config.inc.php: {{ . }}
{{- end }}
{{- end }}
