{{- if .Values.components.roundcube }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "roundcube.fullname" . }}-{{ .Values.roundcube.component }}-env
  namespace: {{ template "roundcube.namespace" . }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
    component: {{ .Values.roundcube.component }}
data:
  env: |
    FORCE_HTTPS={{ .Values.forceHttps }}
{{- end }}
