{{- if .Values.components.roundcube }}
{{- if and (not .Values.roundcube.persistence.data.claimName) .Values.roundcube.persistence.data.enabled  }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "roundcube.fullname" . }}-{{ .Values.roundcube.component }}-data
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.roundcube.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.roundcube.persistence.data.size | quote }}
{{- if .Values.roundcube.persistence.data.storageClass }}
  storageClassName: {{ .Values.roundcube.persistence.data.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
