{{- if .Values.components.database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "roundcube.fullname" . }}-{{ .Values.database.component }}-secret
  namespace: {{ template "roundcube.namespace" . }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
    component: {{ .Values.database.component }}
type: Opaque
stringData:
  {{- if ( and .Values.dbUsername .Values.dbRootPassword .Values.dbName ) }}
  {{- if eq .Values.dbType "pgsql" }}
  POSTGRES_PASSWORD: {{ .Values.dbRootPassword | default "database-root-password" }}
  POSTGRES_DB: {{ .Values.dbName | default "database-name" }}
  POSTGRES_USER: {{ .Values.dbUsername | default "database-user" }}
  {{- end }}
  {{- if eq .Values.dbType "mysql" }}
  MYSQL_ROOT_PASSWORD: {{ .Values.dbRootPassword | default "database-root-password" }}
  MYSQL_DATABASE: {{ .Values.dbName | default "database-name" }}
  MYSQL_PASSWORD: {{ .Values.dbPassword | default "database-password" }}
  MYSQL_USER: {{ .Values.dbUsername | default "database-user" }}
  {{- end }}
  {{- end }}
{{- end }}
