{{- if .Values.components.koel }}
{{- $fullName := include "koel.fullname" . -}}
{{- $dummy := set . "component" .Values.koel.component }}
{{- $component := .component -}}
{{- if .Values.koel.ingress.enabled -}}
{{- if eq .Values.koel.service.defaultProtocol "http" -}}
{{- $dummy := set . "svcPort" .Values.koel.service.ports.http }}
{{- else if eq .Values.koel.service.defaultProtocol "https" -}}
{{- $dummy := set . "svcPort" .Values.koel.service.ports.https }}
{{- end -}}
{{- $svcPort := .svcPort -}}
{{- $ingressPath := .Values.koel.ingress.path -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "koel.fullname" . }}-{{ .Values.koel.component }}
  namespace: {{ template "koel.namespace" . }}
  labels:
    {{- include "koel.labels" . | nindent 4 }}
  {{- with .Values.koel.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.koel.ingress.tls }}
  tls:
  {{- range .Values.koel.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.koel.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-{{ $component }}
              servicePort: {{ $svcPort }}
  {{- end }}
{{- end }}
{{- end }}
