{{- if .Values.components.database }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "koel.fullname" . }}-{{ .Values.database.component }}-secret"
  namespace: {{ template "koel.namespace" . }}
  labels:
    {{- include "koel.standardLabels" . | nindent 4 }}
    component: {{ .Values.database.component }}
type: Opaque
stringData:
  {{- if ( and .Values.database.db_user .Values.database.db_root_password .Values.database.db_name ) }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.db_root_password | default "database-root-password" }}
  MYSQL_DATABASE: {{ .Values.database.db_name | default "database-name" }}
  MYSQL_PASSWORD: {{ .Values.database.db_user.password | default "database-password" }}
  MYSQL_USER: {{ .Values.database.db_user.user | default "database-user" }}
  {{- end }}
{{- end }}
