{{- if .Values.embyPreferences.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.embyPreferences.configmap.name }}
  labels:
    {{- include "emby.labels" . | nindent 4 }}
{{- if .Values.embyPreferences.configmap.labels }}
{{ toYaml .Values.embyPreferences.configmap.labels | indent 4 }}
{{- end }}
{{- with .Values.embyPreferences.configmap.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

data:
# At some point figure out how to use a value/Variable here to be able to specify
# a different file or something.
{{ (tpl (.Files.Glob "configs/41-emby-preferences").AsConfig . ) | indent 2 }}
{{- end -}}

{{- if .Values.certificate.pkcsMangler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.certificate.pkcsMangler.configmap.name }}
  labels:
    {{- include "emby.labels" . | nindent 4 }}
{{- if .Values.certificate.pkcsMangler.configmap.labels }}
{{ toYaml .Values.certificate.pkcsMangler.configmap.labels | indent 4 }}
{{- end }}
{{- with .Values.certificate.pkcsMangler.configmap.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

data:
# At some point figure out how to use a value/Variable here to be able to specify
# a different file or something.
{{ (tpl (.Files.Glob "configs/42-pkcs-mangler").AsConfig . ) | indent 2 }}
{{- end -}}
