{{- if .Values.components.osp_rtmp }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_rtmp.component }}"
  namespace: {{ template "osp.namespace" . }}
  labels:
    {{- include "osp.standardLabels" . | nindent 4 }}
    component: {{ .Values.osp_rtmp.component }}
  annotations:
{{ toYaml .Values.osp_rtmp.service.rtmp.annotations | indent 4 }}
spec:
  type: {{ .Values.osp_rtmp.service.rtmp.type }}
  ports:
    - name: server
      port: {{ .Values.osp_rtmp.service.rtmp.port }}
      protocol: TCP
      targetPort: server
    - name: nginx
      port: {{ .Values.osp_rtmp.service.nginx.port }}
      protocol: TCP
      targetPort: nginx
  selector:
    app: {{ template "osp.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.osp_rtmp.component }}
{{- end }}
