{{- if .Values.components.osp_ejabberd }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_ejabberd.component }}-secret"
  namespace: {{ template "osp.namespace" . }}
  labels:
    {{- include "osp.standardLabels" . | nindent 4 }}
    component: {{ .Values.osp_ejabberd.component }}
type: Opaque
stringData:
  {{- if .Values.osp_ejabberd.password }}
  EJABBERD_PASSWORD: {{ .Values.osp_ejabberd.password | default "osp-ejabberd-password" }}
  {{- end }}
{{- end }}
