{{- if .Values.components.osp_core }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_core.component }}-secret"
  namespace: {{ template "osp.namespace" . }}
  labels:
    {{- include "osp.standardLabels" . | nindent 4 }}
    component: {{ .Values.osp_core.component }}
type: Opaque
stringData:
  {{- if .Values.osp_core.flask }}
  OSP_CORE_SECRETKEY: {{ .Values.osp_core.flask.secret | default "osp-flask-secret" }}
  OSP_CORE_PASSWORD_SALT: {{ .Values.osp_core.flask.salt | default "osp-flask-salt" }}
  {{- end }}
{{- end }}
