{{- if .Values.components.osp_db }}
{{- if (and .Values.volumes.persistence .Values.osp_db.volumes.persistence) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_db.component }}-{{ .Values.osp_db.volumes.data.name }}"
  namespace: {{ template "osp.namespace" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.osp_db.volumes.data.size }}
  accessModes: [ "{{ .Values.osp_db.volumes.data.accessMode }}" ]
{{- if .Values.osp_db.volumes.data.storageClassName }}
  storageClassName: "{{ .Values.osp_db.volumes.data.storageClassName }}"
{{- else if and (not (and .Values.volumes.local_storage .Values.osp_db.volumes.data.local_storage)) .Values.osp_db.volumes.data.storageClass }}
  storageClassName: "{{ template "osp.fullname" . }}-{{ .Values.osp_db.component }}-{{ .Values.osp_db.volumes.data.name }}"
{{- else if and .Values.volumes.local_storage .Values.osp_db.volumes.data.local_storage }}
  storageClassName: "local-storage"
{{- end }}
{{- end }}
{{- end }}
