{{- if .Values.components.osp_db }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_db.component }}"
  namespace: {{ template "osp.namespace" . }}
  labels:
    {{- include "osp.standardLabels" . | nindent 4 }}
    component: {{ .Values.osp_db.component }}
  annotations:
{{ toYaml .Values.osp_db.service.annotations | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: server
      port: {{ .Values.osp_db.port }}
      protocol: TCP
  selector:
    app: {{ template "osp.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.osp_db.component }}
{{- end }}
