{{- if .Values.components.osp_db }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "osp.fullname" . }}-{{ .Values.osp_db.component }}-secret"
  namespace: {{ template "osp.namespace" . }}
  labels:
    {{- include "osp.standardLabels" . | nindent 4 }}
    component: {{ .Values.osp_db.component }}
type: Opaque
stringData:
  {{- if ( and .Values.osp_db.db_user .Values.osp_db.db_root_password .Values.osp_db.db_name ) }}
  MYSQL_ROOT_PASSWORD: {{ .Values.osp_db.db_root_password | default "osp-db-root-password" }}
  MYSQL_DATABASE: {{ .Values.osp_db.db_name | default "osp-db-name" }}
  MYSQL_PASSWORD: {{ .Values.osp_db.db_user.password | default "osp-db-password" }}
  MYSQL_USER: {{ .Values.osp_db.db_user.user | default "osp-db-user" }}
  {{- end }}
{{- end }}
